---
- name: create main config
  template:
    src: redis_exporter.cfg.j2
    dest: "{{ redis_exporter_dirs.config_dir }}/{{ redis_exporter_config_file }}"
    owner: root
    group: "{{ redis_exporter_user_name }}"
    mode: 0640
  notify: restart redis_exporter service
